const alphanumeric = `\\dA-Za-z-`;
const numeric = `0|[1-9]\\d*`;
const partMajor = `(?<major>${numeric})`;
const partMinor = `(?<minor>${numeric})`;
const partPatch = `(?<patch>${numeric})`;
const partPreRelease = `-(?<prerelease>[${alphanumeric}]+(?:\\.[${alphanumeric}]+)*)`;
const partBuild = `\\+(?<build>[${alphanumeric}]+(?:\\.[${alphanumeric}]+)*)`;
const full = `${partMajor}\\.${partMinor}\\.${partPatch}(?:${partPreRelease})?(?:${partBuild})?`;
module.exports = full;
